workspace:
  base: /go
  path: src/github.com/okoeth/starter-golang

pipeline:
  feature-dev-build:
    image: golang
    environment:
     - MONGODB_HOST=
    commands:
      - go version
      # Vendoring hack
      - cp -rf vendor/* /go/src
      - go build
      - go test
    when:
      branch: f-dev-*

  feature-test-build:
    image: golang
    environment:
     - MONGODB_HOST=
    commands:
      - go version
      # Vendoring hack
      - cp -rf vendor/* /go/src
      - go build
      - go test
    when:
      branch: f-test-*

  feature-test-test:
    image: golang
    environment:
     - MONGODB_HOST=mongo
    commands:
      - go test
    when:
      branch: f-test-*

  feature-test-deploy:
    image: okoeth/openshift-client
    environment:
      - INSTANCE=172.30.0.1
      - STORAGE=gluster
      - REPOSITORY=https://github.com/okoeth/starter-golang.git
      - NAMESPACE=ng-${DRONE_BRANCH}
    commands:
      - oc version
      - oc login $INSTANCE:443 -u $OC_USER -p $OC_PASSWORD --insecure-skip-tls-verify
      - cd /go/src/github.com/okoeth/starter-golang/openshift
      - ./createNamespace.sh $NAMESPACE starter
      - ./createBuildSecret.sh $NAMESPACE $GIT_USER $GIT_PASSWORD
      - ./createAppdb.sh $NAMESPACE starter $STORAGE
      - ./createApp.sh $NAMESPACE starter $REPOSITORY
    secrets: [ oc_user, oc_password, git_user, git_password ]
    when:
      branch: f-test-*

services:
  mongo:
    image: centos/mongodb-26-centos7
    environment:
     - MONGODB_USER=user
     - MONGODB_PASSWORD=password
     - MONGODB_DATABASE=starterdb
     - MONGODB_ADMIN_PASSWORD=admin_password
