pipeline:
  build:
    image: golang
    environment:
     - MONGODB_HOST=
    commands:
      - go version
      - go get goji.io
      - go get goji.io/pat
      - go get github.com/golang/mock/gomock
      - go get github.com/golang/mock/mockgen
      - go get gopkg.in/mgo.v2
      - go get gopkg.in/mgo.v2/bson
      - go build
      - go test

  test:
    image: golang
    environment:
     - MONGODB_HOST=mongo
    commands:
      - sleep 5
      - go test

services:
  mongo:
    image: centos/mongodb-26-centos7
    environment:
     - MONGODB_USER=user
     - MONGODB_PASSWORD=password
     - MONGODB_DATABASE=starterdb
     - MONGODB_ADMIN_PASSWORD=admin_password
