workspace:
  base: /go
  path: src/github.com/okoeth/starter-golang

pipeline:
  feature-dev-build:
    image: golang
    environment:
     - MONGODB_HOST=
    commands:
      - go version
      # Vendoring hack
      - cp -rf vendor/* /go/src
      - go build
      - go test
    when:
      branch: f-dev-*

  feature-test-build:
    image: golang
    environment:
     - MONGODB_HOST=
    commands:
      - go version
      # Vendoring hack
      - cp -rf vendor/* /go/src
      - go build
      - go test
    when:
      branch: f-test-*

  feature-test-test:
    image: golang
    environment:
     - MONGODB_HOST=mongo
    commands:
      - go test
    when:
      branch: master

  feature-test-deploy:
    image: okoeth/openshift-client
    environment:
      - NAMESPACE=starter-go-test
    commands:
      - oc version
      - oc login jp1.altemista.cloud:8443 -u $OC_USER -p $OC_PASSWORD --insecure-skip-tls-verify
      - oc project $NAMESPACE
      - cd /go/src/github.com/okoeth/starter-golang/openshift
      - ./clean.sh $NAMESPACE starter-test
      - ./clean.sh $NAMESPACE starterdb-test
      - ./createBuildSecret.sh $NAMESPACE $ $GITHUB_USER $GITHUB_PASSWORD
      - ./createAppdb.sh $NAMESPACE starter aws test
      - ./createApp.sh $NAMESPACE starter https://github.com/okoeth/starter-golang.git test
    secrets: [ oc_user, oc_password, github_user, github_password ]
    when:
      branch: master

services:
  mongo:
    image: centos/mongodb-26-centos7
    environment:
     - MONGODB_USER=user
     - MONGODB_PASSWORD=password
     - MONGODB_DATABASE=starterdb
     - MONGODB_ADMIN_PASSWORD=admin_password
