pipeline:
  build:
    image: golang
    commands:
      - go version
      - go get goji.io
      - go get goji.io/pat
      - go get github.com/golang/mock/gomock
      - go get github.com/golang/mock/mockgen
      - go get gopkg.in/mgo.v2
      - go get gopkg.in/mgo.v2/bson
      - go build
      - go test

