version: '2.0'
services:
  passionator:
    build: .
    ports:
      - "8000:8000" 
    environment:
      - MONGODB_HOST=passionatordb
    networks:
      - default
  passionatordb:
    image: "centos/mongodb-26-centos7"
    ports:
      - "27017:27017" 
    environment:
     - MONGODB_USER=user
     - MONGODB_PASSWORD=password
     - MONGODB_DATABASE=passionatordb
     - MONGODB_ADMIN_PASSWORD=admin_password
    volumes:
      - passionatordb:/data/db
    networks:
     - default

volumes:
  passionatordb:

networks:
  default:
