apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: APPdb-claim
  labels:
    app: APPdb
  annotations:
    volume.alpha.kubernetes.io/storage-class: 'foo'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: 1Gi
